package cn.iocoder.yudao.module.bpm.dal.mysql.senddoc;

import java.util.*;

import cn.iocoder.yudao.framework.common.pojo.PageResult;
import cn.iocoder.yudao.framework.mybatis.core.query.LambdaQueryWrapperX;
import cn.iocoder.yudao.framework.mybatis.core.mapper.BaseMapperX;
import cn.iocoder.yudao.module.bpm.dal.dataobject.senddoc.SendDocDO;
import cn.iocoder.yudao.module.bpm.enums.task.BpmProcessInstanceStatusEnum;
import org.apache.ibatis.annotations.Mapper;
import cn.iocoder.yudao.module.bpm.controller.admin.senddoc.vo.*;

/**
 * 发文 Mapper
 *
 * @author 管理员
 */
@Mapper
public interface SendDocMapper extends BaseMapperX<SendDocDO> {

    default PageResult<SendDocDO> selectPage(SendDocPageReqVO reqVO) {
        return selectPage(reqVO, new LambdaQueryWrapperX<SendDocDO>()
                .eqIfPresent(SendDocDO::getSendDocDraft, reqVO.getSendDocDraft())
                .eqIfPresent(SendDocDO::getSendDocResult, reqVO.getSendDocResult())
                .eqIfPresent(SendDocDO::getDocProperty, reqVO.getDocProperty())
                .eqIfPresent(SendDocDO::getPrimarySendDept, reqVO.getPrimarySendDept())
                .eqIfPresent(SendDocDO::getCopySendDept, reqVO.getCopySendDept())
                .eqIfPresent(SendDocDO::getReportSendDept, reqVO.getReportSendDept())
                .eqIfPresent(SendDocDO::getDeliverSendDept, reqVO.getDeliverSendDept())
                .likeIfPresent(SendDocDO::getSendDocNumber, reqVO.getSendDocNumber())
                .betweenIfPresent(SendDocDO::getSendTime, reqVO.getSendTime())
                .eqIfPresent(SendDocDO::getSignPrintCount, reqVO.getSignPrintCount())
                .eqIfPresent(SendDocDO::getKeepTerm, reqVO.getKeepTerm())
                .eqIfPresent(SendDocDO::getProjectId, reqVO.getProjectId())
                .likeIfPresent(SendDocDO::getSubject, reqVO.getSubject())
                .eqIfPresent(SendDocDO::getUrgencyDegree, reqVO.getUrgencyDegree())
                .eqIfPresent(SendDocDO::getSecretDegree, reqVO.getSecretDegree())
                .eqIfPresent(SendDocDO::getRemark, reqVO.getRemark())
                .eqIfPresent(SendDocDO::getDocSequence, reqVO.getDocSequence())
                .eqIfPresent(SendDocDO::getYear, reqVO.getYear())
                .eqIfPresent(SendDocDO::getKeyWords, reqVO.getKeyWords())
                .likeIfPresent(SendDocDO::getSendDept, reqVO.getSendDept())
                .likeIfPresent(SendDocDO::getDraftPerson, reqVO.getDraftPerson())
                .betweenIfPresent(SendDocDO::getDraftDate, reqVO.getDraftDate())
                .eqIfPresent(SendDocDO::getDraftIdea, reqVO.getDraftIdea())
                .eqIfPresent(SendDocDO::getContactPhone, reqVO.getContactPhone())
                .likeIfPresent(SendDocDO::getResultFileName, reqVO.getResultFileName())
                .eqIfPresent(SendDocDO::getDocSecondClass, reqVO.getDocSecondClass())
                .eqIfPresent(SendDocDO::getDocClass, reqVO.getDocClass())
                .eqIfPresent(SendDocDO::getDealTimelimit, reqVO.getDealTimelimit())
                .eqIfPresent(SendDocDO::getReleasetoout, reqVO.getReleasetoout())
                .eqIfPresent(SendDocDO::getReleasetospecial, reqVO.getReleasetospecial())
                .eqIfPresent(SendDocDO::getReleasetoin, reqVO.getReleasetoin())
                .eqIfPresent(SendDocDO::getUpdatereleaseman, reqVO.getUpdatereleaseman())
                .betweenIfPresent(SendDocDO::getUpdatereleasedate, reqVO.getUpdatereleasedate())
                .eqIfPresent(SendDocDO::getReleasetoother, reqVO.getReleasetoother())
                .eqIfPresent(SendDocDO::getReceiveDocId, reqVO.getReceiveDocId())
                .eqIfPresent(SendDocDO::getCheckoutUserId, reqVO.getCheckoutUserId())
                .betweenIfPresent(SendDocDO::getCheckoutTime, reqVO.getCheckoutTime())
                .eqIfPresent(SendDocDO::getSecretaryidea, reqVO.getSecretaryidea())
                .eqIfPresent(SendDocDO::getSecretaryideaPerson, reqVO.getSecretaryideaPerson())
                .betweenIfPresent(SendDocDO::getSecretaryideaDate, reqVO.getSecretaryideaDate())
                .eqIfPresent(SendDocDO::getDirectoridea, reqVO.getDirectoridea())
                .eqIfPresent(SendDocDO::getDirectorideaPerson, reqVO.getDirectorideaPerson())
                .betweenIfPresent(SendDocDO::getDirectorideaDate, reqVO.getDirectorideaDate())
                .eqIfPresent(SendDocDO::getCouldquery, reqVO.getCouldquery())
                .eqIfPresent(SendDocDO::getVdformpage, reqVO.getVdformpage())
                .eqIfPresent(SendDocDO::getDefaultAccess, reqVO.getDefaultAccess())
                .eqIfPresent(SendDocDO::getPrintbarcode, reqVO.getPrintbarcode())
                .eqIfPresent(SendDocDO::getInforelease, reqVO.getInforelease())
                .eqIfPresent(SendDocDO::getNoreleasecause, reqVO.getNoreleasecause())
                .eqIfPresent(SendDocDO::getAttachFilePath, reqVO.getAttachFilePath())
                .eqIfPresent(SendDocDO::getFiletag, reqVO.getFiletag())
                .eqIfPresent(SendDocDO::getDraftDept, reqVO.getDraftDept())
                .eqIfPresent(SendDocDO::getResponsibleDept, reqVO.getResponsibleDept())
                .eqIfPresent(SendDocDO::getIsexported, reqVO.getIsexported())
                .eqIfPresent(SendDocDO::getIscanexport, reqVO.getIscanexport())
                .eqIfPresent(SendDocDO::getCustomnumber, reqVO.getCustomnumber())
                .eqIfPresent(SendDocDO::getDraftPersonUserid, reqVO.getDraftPersonUserid())
                .eqIfPresent(SendDocDO::getIshavetif, reqVO.getIshavetif())
                .eqIfPresent(SendDocDO::getExPrimarySendDept, reqVO.getExPrimarySendDept())
                .eqIfPresent(SendDocDO::getExCopySendDept, reqVO.getExCopySendDept())
                .eqIfPresent(SendDocDO::getIspolicynorm, reqVO.getIspolicynorm())
                .eqIfPresent(SendDocDO::getFzjgyjTz, reqVO.getFzjgyjTz())
                .eqIfPresent(SendDocDO::getFzjgyjTzPerson, reqVO.getFzjgyjTzPerson())
                .betweenIfPresent(SendDocDO::getFzjgyjTzDate, reqVO.getFzjgyjTzDate())
                .eqIfPresent(SendDocDO::getCustomnumber2, reqVO.getCustomnumber2())
                .eqIfPresent(SendDocDO::getCustomnumber3, reqVO.getCustomnumber3())
                .eqIfPresent(SendDocDO::getHqdept, reqVO.getHqdept())
                .likeIfPresent(SendDocDO::getHqname, reqVO.getHqname())
                .eqIfPresent(SendDocDO::getHqidea, reqVO.getHqidea())
                .betweenIfPresent(SendDocDO::getHqdate, reqVO.getHqdate())
                .likeIfPresent(SendDocDO::getIssuedName, reqVO.getIssuedName())
                .eqIfPresent(SendDocDO::getProofreader, reqVO.getProofreader())
                .betweenIfPresent(SendDocDO::getProofreaderDate, reqVO.getProofreaderDate())
                .eqIfPresent(SendDocDO::getYinzhiren, reqVO.getYinzhiren())
                .eqIfPresent(SendDocDO::getYongyinren, reqVO.getYongyinren())
                .eqIfPresent(SendDocDO::getFenfaren, reqVO.getFenfaren())
                .eqIfPresent(SendDocDO::getDocType, reqVO.getDocType())
                .eqIfPresent(SendDocDO::getSendDocNotion, reqVO.getSendDocNotion())
                .eqIfPresent(SendDocDO::getDocRange, reqVO.getDocRange())
                .eqIfPresent(SendDocDO::getIsunion, reqVO.getIsunion())
                .eqIfPresent(SendDocDO::getUniondepts, reqVO.getUniondepts())
                .eqIfPresent(SendDocDO::getUniondeptscomments, reqVO.getUniondeptscomments())
                .eqIfPresent(SendDocDO::getForceexchangepdf, reqVO.getForceexchangepdf())
                .eqIfPresent(SendDocDO::getIsuploadwordformal, reqVO.getIsuploadwordformal())
                .eqIfPresent(SendDocDO::getTypist, reqVO.getTypist())
                .betweenIfPresent(SendDocDO::getTypistDate, reqVO.getTypistDate())
                .betweenIfPresent(SendDocDO::getThwordupdate, reqVO.getThwordupdate())
                .eqIfPresent(SendDocDO::getFugleidea, reqVO.getFugleidea())
                .likeIfPresent(SendDocDO::getFuglename, reqVO.getFuglename())
                .betweenIfPresent(SendDocDO::getFugledate, reqVO.getFugledate())
                .eqIfPresent(SendDocDO::getOrganize, reqVO.getOrganize())
                .eqIfPresent(SendDocDO::getSendUnitid, reqVO.getSendUnitid())
                .eqIfPresent(SendDocDO::getSendStatus, reqVO.getSendStatus())
                .eqIfPresent(SendDocDO::getAcceptNumber, reqVO.getAcceptNumber())
                .betweenIfPresent(SendDocDO::getAcceptStarttime, reqVO.getAcceptStarttime())
                .betweenIfPresent(SendDocDO::getAcceptEndtime, reqVO.getAcceptEndtime())
                .betweenIfPresent(SendDocDO::getAcceptDelaytime, reqVO.getAcceptDelaytime())
                .eqIfPresent(SendDocDO::getIsNormativeDocument, reqVO.getIsNormativeDocument())
                .eqIfPresent(SendDocDO::getIfimportant, reqVO.getIfimportant())
                .eqIfPresent(SendDocDO::getSecretaryimplementidea, reqVO.getSecretaryimplementidea())
                .eqIfPresent(SendDocDO::getSecretaryimplementideaPerson, reqVO.getSecretaryimplementideaPerson())
                .betweenIfPresent(SendDocDO::getSecretaryimplementideaDate, reqVO.getSecretaryimplementideaDate())
                .eqIfPresent(SendDocDO::getMiniknow, reqVO.getMiniknow())
                .eqIfPresent(SendDocDO::getSelecttype, reqVO.getSelecttype())
                .eqIfPresent(SendDocDO::getIfpigeonhold, reqVO.getIfpigeonhold())
                .eqIfPresent(SendDocDO::getPigeonholeNum, reqVO.getPigeonholeNum())
                .eqIfPresent(SendDocDO::getPigeonholeSeq, reqVO.getPigeonholeSeq())
                .eqIfPresent(SendDocDO::getPigeonholeResult, reqVO.getPigeonholeResult())
                .eqIfPresent(SendDocDO::getProcessInstanceId, reqVO.getProcessInstanceId())
                .eqIfPresent(SendDocDO::getStatus, reqVO.getStatus())
                .betweenIfPresent(SendDocDO::getCreateTime, reqVO.getCreateTime())
                .neIfPresent(SendDocDO::getStatus, BpmProcessInstanceStatusEnum.INVALID.getStatus().shortValue())
                .orderByDesc(SendDocDO::getId));
    }

}
